Feature/feature branch
jamestucker1988/enumerables pull request #3
Opened 2020-10-23 15:53 UTC by nikoescobal

First submission for enumerables project

2020-10-23 19:18 UTC, maelfosso requested changes
# Changes required :red_circle:

Hello,

Thank you for the well-done job so far.
However, there are some missing requirements

1- There is that error into your `main.rb` file
```rb
$ ruby -wc main.rb 
main.rb:51: warning: mismatched indentations at 'end' with 'while' at 40
main.rb:109: syntax error, unexpected end-of-input, expecting `end'
```
Fix it, please

2- There is only one method `my_each` implement and it's not working. Many methods are missing. Kindly add them.

- `my_each_with_index`
- `my_select`
- `my_all?`
` `my_any?`
- `my_none?`
- `my_count`
- `my_map`
- `my_inject`
- `multiply_els`

Each of those methods must return the same thing as the ruby one in all situations. 
- Range
- Pattern
- Block
- Classes

3- Read the comments left below.

Kindly make the suggested changes. 
Once done submit a new code review request
Thanks

Mael FOSSO

2020-10-23 19:18 UTC, maelfosso commented on x.rb
> + puts %i[hello world india].repeat(2)
What is the purpose of this file?
Kindly remove it, please.

2020-10-23 19:18 UTC, maelfosso commented on main.rb
> +#  [1,2,3,4,5].my_each_with_index {|x,y| puts x,y }
Remove all the comments, please.

2020-10-30 16:26 UTC, PhillipUg requested changes
Hey **Captain Kumar & Niko Escobal**, 👋

You did a *great* job on this project! Your `my_each`, `my_each_with_index`, `my_all` and `my_select` methods passed all test cases with no issues. ✔️ 

However, you didn't account for some test cases, with the rest of the methods. Please use the provided test cases below to properly diagnose which test cases are failing and correct them accordingly. 

### Changes Required ♻️ 

- [ ] Make the rest of the methods pass all the test cases provided below:

```
# 4. my_all? (example test cases)
puts 'my_all?'
puts '-------'
p [3, 5, 7, 11].my_all?(&:odd?) # => true
p [-8, -9, -6].my_all? { |n| n < 0 } # => true
p [3, 5, 8, 11].my_all?(&:odd?) # => false
p [-8, -9, -6, 0].my_all? { |n| n < 0 } # => false
# test cases required by tse reviewer
p [1, 2, 3, 4, 5].my_all? # => true
p [1, 2, 3].my_all?(Integer) # => true
p %w[dog door rod blade].my_all?(/d/) # => true
p [1, 1, 1].my_all?(1) # => true
puts

# 5. my_any? (example test cases)
puts 'my_any?'
puts '-------'
p [7, 10, 3, 5].my_any?(&:even?) # => true
p [7, 10, 4, 5].my_any?(&:even?) # => true
p %w[q r s i].my_any? { |char| 'aeiou'.include?(char) } # => true
p [7, 11, 3, 5].my_any?(&:even?) # => false
p %w[q r s t].my_any? { |char| 'aeiou'.include?(char) } # => false
# test cases required by tse reviewer
p [3, 5, 4, 11].my_any? # => true
p [1, nil, false].my_any?(1) # => true
p [1, nil, false].my_any?(Integer) # => true
p %w[dog door rod blade].my_any?(/z/) # => false
p [1, 2, 3].my_any?(1) # => true
puts

# 6. my_none? (example test cases)
puts 'my_none?'
puts '--------'
p [3, 5, 7, 11].my_none?(&:even?) # => true
p %w[sushi pizza burrito].my_none? { |word| word[0] == 'a' } # => true
p [3, 5, 4, 7, 11].my_none?(&:even?) # => false
p %w[asparagus sushi pizza apple burrito].my_none? { |word| word[0] == 'a' } # => false
# test cases required by tse reviewer
p [1, 2, 3].my_none? # => false
p [1, 2, 3].my_none?(String) # => true
p [1, 2, 3, 4, 5].my_none?(2) # => false
p [1, 2, 3].my_none?(4) # => true
puts

# 7. my_count (example test cases)
puts 'my_count'
puts '--------'
p [1, 4, 3, 8].my_count(&:even?) # => 2
p %w[DANIEL JIA KRITI dave].my_count { |s| s == s.upcase } # => 3
p %w[daniel jia kriti dave].my_count { |s| s == s.upcase } # => 0
# test cases required by tse reviewer
p [1, 2, 3].my_count # => 3
p [1, 1, 1, 2, 3].my_count(1) # => 3
puts

# 8. my_map
puts 'my_map'
puts '------'
p [1, 2, 3].my_map { |n| 2 * n } # => [2,4,6]
p %w[Hey Jude].my_map { |word| word + '?' } # => ["Hey?", "Jude?"]
p [false, true].my_map(&:!) # => [true, false]
my_proc = proc { |num| num > 10 }
p [18, 22, 5, 6].my_map(my_proc) { |num| num < 10 } # => true true false false
puts

# 9. my_inject
puts 'my_inject'
puts '---------'
p [1, 2, 3, 4].my_inject(10) { |accum, elem| accum + elem } # => 20
p [1, 2, 3, 4].my_inject { |accum, elem| accum + elem } # => 10
p [5, 1, 2].my_inject('+') # => 8
p (5..10).my_inject(2, :*) # should return 302400
p (5..10).my_inject(4) { |prod, n| prod * n } # should return 604800
```

### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Phillip Musiime

2020-11-06 15:25 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @ . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 
- [ ] Project should have a working `my_each` method. See inline comment.
- [ ] Project should have a working `my_each_with_index` method. See inline comment.
- [ ] Project should have a working `my_select` method. See inline comment.
- [ ] Project should have a working `my_all` method. See inline comment.
- [ ] Project should have a working `my_map` method. See inline comment.

- [ ] Missing `my_inject` method. The project should have a working `my_inject`.

### `inject`` is an Enumerable that has these characteristics:
- Returns a `LocalJumpError` when no block is given and no symbol is passed as an argument.
```
[1, 2, 3].inject
# LocalJumpError (no block given)
```

- it does not modify/change the original array/range/hash.

- it can accept an initial value and/or a symbol as an argument.
```
[1, 2, 3].inject(2, :*)
# 12
```

[Enumerable#inject](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-inject)

- [ ] MIssing `multiply_els` method. 

- [ ] All commented code, that is not for a production output should be deleted from the `main.rb`

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-11-06 15:25 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_map` is not working as the original `map` method, also is not passing all test cases.

### `map` is an Enumerable that has these characteristics:
- Returns an Enumerator if no block is given.
```
[1, 2, 3].map
# #<Enumerator: [1, 2, 3]:map>
```
- Returns a **new array** with the results of running a block
```
[1, 2, 3].map { |num| num * 2 }
# [2, 4, 6]
```
- doesn't change/modify the original array/range/hash
- can accept a proc as an argument
```
['1', '2', '3'].map(&:to_i)
# [1, 2, 3]
```
[Enumerable#map](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-map)

2020-11-06 15:25 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_each` is not working as the original `each` method, also is not passing all test cases.

### `each` is an Enumerator that has these characteristics: 
- Returns an Enumerator if no block is given.
```
[1, 2, 3].each 
# #<Enumerator: [1, 2, 3]:each>
````
- It does not change or modify the original array/range

- it returns the array/range/hash itself if a block is given.
```
[1, 2, 3].each { |num| num }
# [1, 2, 3]
(1..3).each { |num| num * 2 }
# 1..3
````
- it applies the block for each element inside the array/range/hash
```
[1, 2, 3].each { |num| puts num }
# 1
# 2
# 3
# => [1, 2, 3]
```
[Enumerator#each](https://ruby-doc.org/core-2.7.2/Enumerator.html#method-i-each)

2020-11-06 15:25 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_each_with_index` is not working as the original `each_with_index` method, also is not passing all test cases.

### `each_with_index` is an Enumerable that has these characteristics: 
- Returns an Enumerator if no block is given.
```
[1, 2, 3].each_with_index
# #<Enumerator: [1, 2, 3]:each_with_index>
````
- It does not change or modify the original array/range

- it returns the array/range/hash itself if a block is given.
```
[1, 2, 3].each_with_index { |num, idx| num }
# [1, 2, 3]
(1..3).each { |num, idx| num * idx }
# 1..3
````
- it applies the block for each element inside the array/range/hash
```
[1, 2, 3].each_with_index { |num, idx| puts num, idx }
# 1
# 0
# 2
# 1
# 3
# 2
# => [1, 2, 3]
```
[Enumerator#each](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-each_with_index)

2020-11-06 15:25 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_all` is not working as the original `all?` method, also is not passing all test cases. 

- [ ] the method name should have `?` question mark appended to the end of the method name.

### `all?` is an Enumerable that has these characteristics:
- Returns `true` if all elements are not false.
```
[1, 'string', true].all?
# true
```
- Returns `false` if it finds at least one element that is not true
```
[1, 'string', nil].all?
# false
```
- it doesn't change the original array/range/hash
- it can accept as arguments a Class, a RegEx, or a pattern, and returns true or false depending if the values in the array/range/hash match the condition
- it can use a block but it is not necessary to make the method work

[Enumerable#all?](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-all-3F)

2020-11-06 15:25 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_select` is not working as the original `select` method, also is not passing all test cases.

### `select` is an Enumerable that has these characteristics:
- Returns an Enumerator if no block is given.
```
[1, 2, 3].select
# #<Enumerator: [1, 2, 3]:select>
```
- Returns a **new array** with the results that match the condition in the block
```
[1, 2, 3].select { |num| num > 2 }
# [3]
```
- doesn't change/modify the original array/range/hash

[Enumerable#select](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-select)

2020-11-10 11:43 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 
### Hi @jamestucker1988 and @nikoescobal 
Kudos :muscle:  for coming this far. Your `my_any` and `my_none` methods pass all test cases.

However, there are some issues that need to be fixed before your project can be approved.

## [REQUIRED]

Do review the following methods and make sure they pass all test cases

`my_each`
`my_each_with_index`
`my_select`
`my_all`
`my_count`
`my_map`
`my_inject`

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2020-11-10 16:19 UTC, jubaan requested changes
# Status: Changes Required 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes 
### [Mandatory] 

- [x]  should have a working `my_each`. See inline comment.
- [x]  should have a working `my_each_with_index`. See inline comment.
- [x]  should have a working `my_select`. See inline comment.
- [x]  should have a working `my_all?`. See inline comment.
- [x]  should have a working `my_count`. See inline comment.
- [x]  should have a working `my_map`. See inline comment.
- [x]  should have a working `my_inject`. See inline comment.

## Keep up the great work  and Happy Coding  !!

2020-11-10 16:19 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_each_with_index` is not working as the original `each` method, also is not passing all test cases.

### `each` is an Enumerator that has these characteristics: 
- When a block is given when `self` is a hash behaves like #each calls the given block once for each element in self.
```ruby

# each_with_index

output = ''
block = proc { |num| output += num.to_s}

{1=>1, 2=>2, 3=>3}.each_with_index(&bloc)

output # [1, 1], [2, 2], [3, 3]

# my_each_with_index

output = ''
block = proc { |num| output += num.to_s}

{1=>1, 2=>2, 3=>3}.my_each_with_index(&bloc)

output # 123"
```

[Enumerator#each](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-each_with_index)

2020-11-10 16:19 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_all` is not working as the original `all?` method, also is not passing all test cases. 

### `all?` is an Enumerable that has these characteristics:
- if no block is given returns `false` when on of the elements is `nil` or `false`.
```
[1,2,3].each # true
[1,2,nil].each # false

[1,2,3].my_each # true
[1,2,nil].my_each # true
```
- it can accept as arguments a Class, a RegEx, or a pattern, and returns true or false depending if the values in the array/range/hash match the condition
```
[1, 2, 3].all?(Numeric) # true
[1, 2, 3].all?(String) # false

[1, 2, 3].my_all?(Numeric) # true
[1, 2, 3].my_all?(String) # true
```

[Enumerable#all?](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-all-3F)

2020-11-10 16:19 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_count` is not working as the original `count` method, also is not passing all test cases. 

### `count` is an Enumerable that has these characteristics:
- Returns the count of elements inside an array/range/hash.
- When a block is given it returns the count of elements that match the condition
- Does not mutate the original array

```ruby
[1, 2, 3].count # 3
(0..2).count # 3
[1,2,3].count(1) #1
[1, 2, 3].count { |num| num > 2 } # 1

```
[Enumerable#count](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-count)

2020-11-10 16:19 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_select` is not working as the original `select` method, also is not passing all test cases.

### `select` is an Enumerable that has these characteristics:
- Returns a **new array** with the results that match the condition in the block
```ruby
[1, 2, 3].select { |num| num > 2 } # [3]
(1..3).select { |num| num > 2 } # [3]
```
- doesn't change/modify the original array/range/hash

[Enumerable#select](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-select)

2020-11-10 16:19 UTC, jubaan commented on main.rb
> +  end
- [ ] `my_map` is not working as the original `map` method, also is not passing all test cases.

### `map` is an Enumerable that has these characteristics:
- Returns an Enumerator if no block is given.
```
[1, 2, 3].map
# #<Enumerator: [1, 2, 3]:map>
```
- Returns a **new array** with the results of running a block
```
[1, 2, 3].map { |num| num * 2 }
# [2, 4, 6]
```
- doesn't change/modify the original array/range/hash
- can accept a proc as an argument
```
['1', '2', '3'].map(&:to_i)
# [1, 2, 3]
```
[Enumerable#map](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-map)

2020-11-10 16:19 UTC, jubaan commented on main.rb
> +    end
- [ ] `my_inject` is not working as the original `inject` method, also is not passing all test cases.

### `inject`` is an Enumerable that has these characteristics:
- Returns a `LocalJumpError` when no block is given and no symbol is passed as an argument.
```
[1, 2, 3].inject
# LocalJumpError (no block given)
```

- it does not modify/change the original array/range/hash.

- it can accept an initial value and/or a symbol as an argument.
```
[1, 2, 3].inject(2, :*)
# 12
```

[Enumerable#inject](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-inject)

2020-11-11 11:53 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @nikoescobal and @jamestucker1988  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
:+1: You have a very good progress, you are almost there
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 

- [ ] Please fix this error :point_down:
```ruby
main.rb:139: warning: mismatched indentations at 'end' with 'def' at 137
```

- [ ] Please remove all of the inline commented codes

- [ ] The issue link you provided in your readme file, doesn't work, fix it

- [ ] Twitter and linkedin links of Anand Kumar aren't working, please fix them by adding the working ones if you have them

- [ ] You are missing `my_count` method, please implement it as well

- [ ] I tested your codes with the following values:
```ruby
ARRAY_SIZE = 100
LOWEST_VALUE = 0
HIGHEST_VALUE = 9

  let(:array) { Array.new(ARRAY_SIZE) { rand(LOWEST_VALUE...HIGHEST_VALUE) } }
  let(:block) { proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } }
  let(:words) { %w[dog door rod blade] }
  let(:range) { Range.new(5, 50) }
  let(:hash) { { a: 1, b: 2, c: 3, d: 4, e: 5 } }
  let(:numbers) { [1, 2i, 3.14] }
  let!(:array_clone) { array.clone }
```
### Results: 
```bash
I ran 79 tests
18 test cases failed
```

### Summary of failing tests:
:point_right: The following enumerables: `#my_each, #my_each_with_index, #my_select, #my_all?, #my_map, #my_inject` have failed 13 tests in total => Read the details inline comments in your codes
:point_right: Enumerable: `#my_count` is not implemented this caused the failure of 5 test cases => Implement it

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)
 _slack:_ `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +  #  [1, 2, 3].my_each { |elem| print "#{elem + 1} " }
Remove this commented codes

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +  end
# #my_each, should:
1. when a block is given when self is a hash behaves like #each calls the given block once for each element in self

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +  end
# #my_each_with_index 

2. when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +  end
# #my_select should: 
3. returns an enumerator if no block is given

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +  end
# #my_all? should:
4. when no block or argument is given returns false when one of the collection members are false or nil
5. when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
6. when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +# p [1, 1, 1].my_all?(1) # => true
Remove the commented codes

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +  end
# #my_map should:
7.  returns an Enumerator if no block is given
8. executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

2020-11-11 11:53 UTC, descholar-ceo commented on main.rb
> +  end
# #my_inject should:
9.  raises a "LocalJumpError" when no block or argument is given
10. searches for the longest word in an array of strings
11. when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block::range
12. when a symbol is specified without an initail value combines each element of the collection by applying the symbol as a named method
13. when a symbol is specified without an initail value combines each element of the collection by applying the symbol as a named method:range

2020-11-12 17:49 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Captain Kumar & Niko Escobal** 
Good job with the improvements to your project :muscle:  :muscle: 
You still need to make some improvements:

- [ ] Fix rubocop offenses
- [ ] your Enumerable module give me the next error message "main.rb:212:in `each': no block given (LocalJumpError)".
- [ ] remove tests in main.rb, or move them to a different file.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-11-13 07:04 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 

Congratulations on making all the requested changes and getting this project approved. :+1:

You can merge this branch into the develop branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as: **Phillip Musiime**

2020-12-08 07:55 UTC, merged